---
abstract: tag
author:
  - 'Marc Chantreux <khatar@phear.org>'
build_requires:
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: xml-tag
requires:
  Exporter: 0
  Modern::Perl: 0
  strict: 0
version: 0.2
